# Generated by Django 4.1.4 on 2022-12-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=60)),
                ('picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField()),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('genere', models.CharField(max_length=60)),
                ('rating', models.IntegerField()),
                ('parent_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myapi.channel')),
            ],
        ),
    ]
