# Generated by Django 4.1.4 on 2022-12-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_channel_parent_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parent_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannels', to='myapi.channel'),
        ),
    ]
