# Generated by Django 4.1.4 on 2022-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_channel_parent_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('parent_channel', models.ManyToManyField(blank=True, related_name='channels', to='myapi.channel')),
            ],
        ),
    ]
